### PR TITLE
WIP: Subcategories creation.

### LINKED ISSUE #34: Subcategories are not created
The category sub is not created in our createCategories function: https://share.getcloudapp.com/L1uYQry2 

It should be created with the slug /category/aciform/sub

### PR DESCRIPTION
**Pull request by v9ai**
Fixes: https://github.com/staticfuse/gatsby-theme-publisher/issues/34

### CODE REVIEW

**Comment by justinwhall** [comment]
This great! Thank you. 🙏 Would it be possible to disable prettier and let eslint do its thing and resubmit for sake of code consistency?

**Comment by nicolad** [comment]
> This great! Thank you.  Would it be possible to disable prettier and let eslint do its thing and resubmit for sake of code consistency?

Sure.

**Comment by nicolad** [comment]
@justinwhall I need little hint, on server-side I got category with it's subcategory:

image

but on front-end, the same query did not returned the subcategory:

image

**Comment by justinwhall** [comment]
Oh I see. I think what you want here is for the query is more like:
```
    categories(first: 100) {
      pageInfo {
        hasNextPage
        endCursor
      }
      nodes {
        id
        name
        categoryId
        slug
        posts {
          nodes {
            ...BlogPreviewFragment
          }
        }
        children {
          nodes {
            posts {
              nodes {
                ...BlogPreviewFragment
              }
            }
          }
        }
      }
    }
```

Also, we made a pretty significant change to the repo to support yarn workspaces and multi theme development which sort of blew up this PR.

**Pull request closed without merging**
